# Build Hugo Container
FROM {{ dockerUser + "/" + buildImageName + ":" + buildImageVersion }}
LABEL maintainer="{{ dockerUser }} <{{ dockerUserEmail }}>"
USER root

ENV HUGO_VERSION={{ finalImageVersion }}

# Install Software
RUN wget -O /tmp/hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" && \
  tar zxvf /tmp/hugo.tar.gz -C /tmp && \
  mv /tmp/hugo /usr/bin/hugo && \
  rm -rf /tmp/* && \
  mkdir /project && \
  chown "${ALPINE_USER}":"${ALPINE_USER}" /project

USER ${ALPINE_USER}
EXPOSE 1330/tcp
VOLUME /project
WORKDIR /project

# Configure Hugo To Start In Default Mode
ENTRYPOINT ["/usr/bin/hugo"]
CMD ["help"]
